# Change these first
owner: censecar # Your GitHub organization or username, where this repository lives
repo: censecar # The name of this repository

sites:
  - name: SIMA (MANIFIESTOS)
    url: http://200.12.125.74
    maxResponseTime: 10000
    icon: https://www.censecar.com.mx/apiv2/assets/images/ico/favicon.ico
  - name: SAAIT (FIANZAS)
    url: http://200.12.125.73/Login
    maxResponseTime: 10000
    icon: https://www.censecar.com.mx/apiv2/assets/images/ico/favicon.ico
  - name: SAAIT v2.0 (FIANZAS)
    url: http://200.12.125.76/Login
    maxResponseTime: 10000
    icon: https://www.censecar.com.mx/apiv2/assets/images/ico/favicon.ico
  - name: Manifiestos (NUEVO)
    url: https://manifiestos.censecar.com.mx
    maxResponseTime: 10000
    icon: https://www.censecar.com.mx/apiv2/assets/images/ico/favicon.ico
  - name: Contrato Digital (CARTA PORTE)
    url: https://contratodigital.online
    maxResponseTime: 10000
    icon: https://www.censecar.com.mx/apiv2/assets/images/ico/favicon.ico

assigness:
  - hklabl13
  - censecar

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  status-website:
  #themeUrl: https://www.censecar.com.mx/facturacion/assets/css/style-up.css
  theme: night
  favicon: https://www.censecar.com.mx/facturacion/app-assets/images/ico/favicon.ico
  baseUrl: /censecar
  logoUrl: https://www.censecar.com.mx/facturacion/app-assets/images/logo/censecar.jpg
  name: CenSeCar
  introTitle: "En este sitio podrá verificar el estatus de nuestros sistemas, en caso de caída o cualquier otra incidencia"
  introMessage: Valida en tiempo real la disponibilidad de los servicios CenSeCar
  navbar:
    - title: Status
      href: /
    - title: CenSeCar
      href: https://www.censecar.com.mx
      #href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
